#!/bin/bash
DIR=/home/wolpraynode
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
#NODE_PATH= /home/wolpraynode/servidor/node_modules/
NODE=/usr/bin/node

test -x $NODE || exit 0

function start_app {
    touch $DIR/logs/wolpray.log
  NODE_ENV=production 
  nohup "$NODE" "$DIR/servidor/index.js" 1>>"$DIR/logs/wolpray.log" 2>&1 &
  echo $! > "$DIR/pids/wolpray.pid"
}

function stop_app {
  kill `cat $DIR/pids/wolpray.pid`
}

case $1 in
   start)
      start_app ;;
    stop)
      stop_app ;;
    restart)
      stop_app
      start_app
      ;;
    *)
      echo "usage: wolpray {start|stop}" ;;
esac
exit 0